version: 2

models:
  - name: gold_cost_insights
    description: "Business-ready cost insights with daily summaries and trend analysis"
    columns:
      - name: account_id
        description: "Unique identifier for the Databricks account"
        tests:
          - not_null
      - name: workspace_id
        description: "Unique identifier for the workspace"
        tests:
          - not_null
      - name: usage_date
        description: "Date of the cost analysis"
        tests:
          - not_null
      - name: day_type
        description: "Classification of weekday vs weekend"
        tests:
          - accepted_values:
              values: ['Weekday', 'Weekend']
      - name: total_daily_usage
        description: "Total usage quantity for the day"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: jobs_compute_usage
        description: "Usage quantity for Jobs Compute services"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: interactive_compute_usage
        description: "Usage quantity for Interactive Compute services"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: sql_warehouse_usage
        description: "Usage quantity for SQL Warehouse services"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: serverless_usage
        description: "Usage quantity for Serverless services"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: jobs_compute_pct
        description: "Percentage of total usage from Jobs Compute"
        tests:
          - dbt_utils.expression_is_true:
              expression: "between 0 and 100"
      - name: daily_change_pct
        description: "Percentage change from previous day"
      - name: usage_7day_avg
        description: "7-day moving average of daily usage"
      - name: daily_usage_rank
        description: "Daily ranking of workspace by usage within account"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 1"
