version: 2

models:
  - name: silver_usage_summary
    description: "Cleaned and summarized billing usage data with service categorization"
    columns:
      - name: account_id
        description: "Unique identifier for the Databricks account"
        tests:
          - not_null
      - name: workspace_id
        description: "Unique identifier for the workspace"
        tests:
          - not_null
      - name: usage_date
        description: "Date of the usage event"
        tests:
          - not_null
      - name: sku_name
        description: "SKU name for the billable service"
        tests:
          - not_null
      - name: service_category
        description: "Categorized service type (Jobs Compute, Interactive Compute, etc.)"
        tests:
          - not_null
          - accepted_values:
              values: ['Jobs Compute', 'Interactive Compute', 'SQL Warehouse', 'Delta Live Tables', 'Serverless', 'Storage', 'Other']
      - name: compute_type
        description: "Type of compute (Photon, Standard, Premium)"
        tests:
          - accepted_values:
              values: ['Photon', 'Standard', 'Premium', 'Unknown']
      - name: usage_quantity
        description: "Quantity of usage for the billing period"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: cloud
        description: "Cloud provider (AWS, Azure, GCP)"
      - name: day_type
        description: "Classification of weekday vs weekend"
        tests:
          - accepted_values:
              values: ['Weekday', 'Weekend']
      - name: usage_year
        description: "Year of the usage event"
      - name: usage_month
        description: "Month of the usage event"
        tests:
          - dbt_utils.expression_is_true:
              expression: "between 1 and 12"
