version: 2

models:
  - name: bronze_billing_usage
    description: "Raw billing usage data from Databricks system tables with minimal transformation"
    columns:
      - name: account_id
        description: "Unique identifier for the Databricks account"
        tests:
          - not_null
      - name: workspace_id
        description: "Unique identifier for the workspace"
        tests:
          - not_null
      - name: record_id
        description: "Unique identifier for each billing record"
        tests:
          - unique
          - not_null
      - name: usage_date
        description: "Date of the usage event"
        tests:
          - not_null
      - name: usage_quantity
        description: "Quantity of usage for the billing period"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: sku_name
        description: "SKU name for the billable service"
        tests:
          - not_null
      - name: usage_unit
        description: "Unit of measurement for usage (e.g., DBU, GB)"
        tests:
          - not_null
      - name: cloud
        description: "Cloud provider (AWS, Azure, GCP)"
      - name: bronze_processed_at
        description: "Timestamp when the record was processed in the bronze layer"
