version: 2

# NOTE: Sources are not used in the simplified version
# We reference system tables directly to avoid catalog/schema conflicts
# This file is kept for documentation purposes only

sources:
  - name: system
    description: "Databricks system tables containing operational data"
    tables:
      - name: billing_usage
        description: "Billable usage across the account - Free to use with 365 days retention"
        identifier: "system.billing.usage"
        columns:
          - name: account_id
            description: "Account identifier"
          - name: workspace_id
            description: "Workspace identifier"
          - name: sku_name
            description: "SKU name for the billable service"
          - name: usage_quantity
            description: "Quantity of usage for the billing period"
          - name: usage_date
            description: "Date of usage"
          - name: usage_unit
            description: "Unit of measurement (e.g., DBU, GB)"
          - name: cloud
            description: "Cloud provider (AWS, Azure, GCP)"
          - name: record_id
            description: "Unique identifier for each billing record"
          - name: ingestion_date
            description: "Date when the record was ingested"