version: 2

sources:
  - name: system
    description: "Databricks system tables containing operational data"
    tables:
      - name: billing_usage
        description: "Billable usage across the account"
        identifier: "`system`.`billing`.`usage`"
        columns:
          - name: account_id
            description: "Account identifier"
          - name: workspace_id
            description: "Workspace identifier"
          - name: sku_name
            description: "SKU name for the billable service"
          - name: usage_quantity
            description: "Quantity of usage for the billing period"
          - name: usage_date
            description: "Date of usage"
            
      - name: compute_node_timeline
        description: "Node utilization metrics for compute resources"
        identifier: "`system`.`compute`.`node_timeline`"
        columns:
          - name: account_id
            description: "Account identifier"
          - name: workspace_id
            description: "Workspace identifier"
          - name: cluster_id
            description: "Cluster identifier"
          - name: timestamp
            description: "Timestamp of the metric collection"
            
      - name: access_workspaces_latest
        description: "Latest workspace metadata and configuration"
        identifier: "`system`.`access`.`workspaces_latest`"
        columns:
          - name: account_id
            description: "Account identifier"
          - name: workspace_id
            description: "Workspace identifier"
          - name: workspace_name
            description: "Name of the workspace"
            
      - name: compute_warehouses
        description: "SQL warehouse configurations and metadata"
        identifier: "`system`.`compute`.`warehouses`"
        columns:
          - name: account_id
            description: "Account identifier"
          - name: workspace_id
            description: "Workspace identifier"
          - name: warehouse_id
            description: "SQL warehouse identifier"
            
      - name: lakeflow_jobs
        description: "Job configurations and metadata"
        identifier: "`system`.`lakeflow`.`jobs`"
        columns:
          - name: account_id
            description: "Account identifier"
          - name: workspace_id
            description: "Workspace identifier"
          - name: job_id
            description: "Job identifier"
